### PR TITLE
Various fixes

### LINKED ISSUE #5: Error on solidity file open
Greetings,
I'm getting this error when i'm opening some solidity files.

```
TypeError: Cannot read property '0' of null 
at errors.map.err (~/.atom/packages/linter-solidity/lib/compiler.js:18:67) 
at Array.map (native) 
at parseErrors (~/.atom/packages/linter-solidity/lib/compiler.js:15:6) 
at Object. (~/.atom/packages/linter-solidity/lib/compiler.js:45:32) 
at Module._compile (module.js:413:34) 
at Object.Module._extensions..js (module.js:422:10) 
at Module.load (module.js:357:32) 
at Function.Module._load (module.js:314:12) 
at Function.Module.runMain (module.js:447:10) 
at startup (node.js:154:18)
```

### PR DESCRIPTION
**Pull request by h3ph4est7s**
Syntax corrections,
Add support for DocString (natspec) errors,
IDE config dir ignored
fixes: #5

### CODE REVIEW

**Comment by Latrasis** [comment]
Hi ppanos! Thank you for the work! I'll check this out.

**Comment by Latrasis** [comment]
Can you elaborate on the Docstring/Natspec errors?

**Comment by h3ph4est7s** [comment]
The errors have to do with incomplete docstring syntax more info about the spec can be found [here](https://github.com/ethereum/wiki/wiki/Ethereum-Natural-Specification-Format).
Relevant code elaborating about the errors can be found [here](https://github.com/ethereum/solidity/blob/14d6b0b2d6b35013494e585fef6a88b3e3fa2b5e/libsolidity/parsing/DocStringParser.cpp) and [here](https://github.com/ethereum/solidity/blob/14d6b0b2d6b35013494e585fef6a88b3e3fa2b5e/libsolidity/analysis/DocStringAnalyser.cpp) searching for the `appendError` function calls.
Also there is a problem in the representation of docstring related errors through the compiler, it doesn't print line numbers and positions regarding the error.
I opened an issue regarding this problem [here](https://github.com/ethereum/solidity/issues/1111).

**Comment by Latrasis** [comment]
Hi @h3ph4est7s, I just wanted to say I'm sincerely sorry for not following up your PR for all this time. I don't know how or why I didn't get back to you. I know it doesn't mean much at this point, but thank you for your time and work.

**Comment by Latrasis** [comment]
@h3ph4est7s: Closing this for now.

**Pull request closed without merging**
